import {
  TaskType,
  TaskStatus,
  ACCOUNTS,
  type Task,
  type ProposedJournalEntry,
} from "../../types";

export const INITIAL_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Monthly Payroll Processing",
    description: "Post monthly payroll journal entry for all employees",
    type: TaskType.POST_JOURNAL_ENTRY,
    status: TaskStatus.PENDING_RUN,
    createdAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "task-2",
    title: "Office Rent Payment",
    description: "Record monthly office rent expense",
    type: TaskType.POST_JOURNAL_ENTRY,
    status: TaskStatus.PENDING_RUN,
    createdAt: "2024-10-15T14:00:00Z",
  },
  {
    id: "task-3",
    title: "Reverse Incorrect Payroll Entry",
    description:
      "Reverse the payroll entry posted on Oct 15th due to calculation error",
    type: TaskType.REVERSE_JOURNAL_ENTRY,
    status: TaskStatus.PENDING_RUN,
    createdAt: "2024-10-20T11:30:00Z",
  },
  {
    id: "task-4",
    title: "Reverse Duplicate Revenue Entry",
    description: "Reverse duplicate revenue recognition entry from last month",
    type: TaskType.REVERSE_JOURNAL_ENTRY,
    status: TaskStatus.PENDING_RUN,
    createdAt: "2024-10-18T16:45:00Z",
  },
];

const MIN_LINE_ITEMS = 2;
const MAX_LINE_ITEMS = 10;
const MIN_AMOUNT = 100;
const MAX_AMOUNT = 10_000;

const DESCRIPTIONS = [
  "Automated journal entry",
  "Scheduled posting",
  "Routine accounting automation",
  "System generated entry",
  "Recurring journal entry",
  "Automated adjustment",
];

const MEMO_TEMPLATES = [
  "Automated debit",
  "Automated credit",
  "Generated by task runner",
  "System generated entry line",
  "LLM suggested entry line",
];

const randomInt = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min + 1)) + min;

const pickRandom = <T>(items: readonly T[]): T => {
  const index = randomInt(0, items.length - 1);
  return items[index];
};

const generateLineItemId = () => {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `li-${crypto.randomUUID()}`;
  }

  return `li-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
};

const buildRandomDate = () => {
  const now = Date.now();
  const daysBack = randomInt(0, 60);
  const randomDate = new Date(now - daysBack * 24 * 60 * 60 * 1000);
  return randomDate.toISOString().split("T")[0];
};

const distributeAmount = (count: number, total: number): number[] => {
  const minTotal = count * MIN_AMOUNT;
  const maxTotal = count * MAX_AMOUNT;

  if (total < minTotal || total > maxTotal) {
    throw new Error("Total amount outside valid bounds for distribution.");
  }

  if (count <= 0) {
    return [];
  }

  if (count === 1) {
    return [total];
  }

  const base = total - minTotal;

  for (let attempt = 0; attempt < 500; attempt += 1) {
    const weights = Array.from({ length: count }, () => Math.random() || 0.0001);
    const weightSum = weights.reduce((sum, weight) => sum + weight, 0);
    const extras = weights.map((weight) =>
      Math.round((weight / weightSum) * base)
    );
    const extrasSum = extras.reduce((sum, value) => sum + value, 0);
    let difference = base - extrasSum;

    let index = 0;
    while (difference !== 0 && index < count * 10) {
      const target = index % count;
      const direction = difference > 0 ? 1 : -1;
      const nextExtra = extras[target] + direction;
      const proposedAmount = MIN_AMOUNT + nextExtra;
      if (proposedAmount >= MIN_AMOUNT && proposedAmount <= MAX_AMOUNT) {
        extras[target] = nextExtra;
        difference -= direction;
      }
      index += 1;
    }

    if (difference !== 0) {
      continue;
    }

    const amounts = extras.map((extra) => MIN_AMOUNT + extra);
    if (amounts.every((amount) => amount >= MIN_AMOUNT && amount <= MAX_AMOUNT)) {
      return amounts;
    }
  }

  throw new Error("Failed to distribute amount within constraints.");
};

export const generateRandomJournalEntry = (): ProposedJournalEntry => {
  const totalLineItems = randomInt(MIN_LINE_ITEMS, MAX_LINE_ITEMS);
  const debitCount = randomInt(1, totalLineItems - 1);
  const creditCount = totalLineItems - debitCount;

  const minTotal = Math.max(debitCount, creditCount) * MIN_AMOUNT;
  const maxTotal = Math.min(debitCount, creditCount) * MAX_AMOUNT;
  const totalAmount = randomInt(minTotal, maxTotal);

  const debitAmounts = distributeAmount(debitCount, totalAmount);
  const creditAmounts = distributeAmount(creditCount, totalAmount);

  const lineItems = [
    ...debitAmounts.map((amount) => ({
      id: generateLineItemId(),
      account: pickRandom(ACCOUNTS),
      debit: amount,
      credit: 0,
      memo: pickRandom(MEMO_TEMPLATES),
    })),
    ...creditAmounts.map((amount) => ({
      id: generateLineItemId(),
      account: pickRandom(ACCOUNTS),
      debit: 0,
      credit: amount,
      memo: pickRandom(MEMO_TEMPLATES),
    })),
  ].sort(() => Math.random() - 0.5);

  return {
    date: buildRandomDate(),
    description: pickRandom(DESCRIPTIONS),
    lineItems,
  };
};
